FROM --platform=$TARGETPLATFORM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY . .

ENV NODE_ENV=production

FROM base AS release

EXPOSE 3000

CMD ["node", "src/index.js"]
